### ISSUE TITLE
Use click instead of hover on hamburger menu

### ISSUE THREAD

**Issue by jluangphasy** [goodwid/goodwin-portfolio#8]
On mobile, hover won't work. Your visitors won't be able to see your menu items.

I would use the jQuery on('click') and toggle() methods to fix this.

**Comment by goodwid** [comment]
Hover translates to click on mobile.  It was CSS for the assignment, but I agree, jquery would be better.

**Comment by goodwid** [comment]
Converted CSS hover to jQuery event handlers.
